name: release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version name from the tags
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" | sed 's/v//' >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Release
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_TOKEN }}'
          galaxy_version: '${{ env.RELEASE_VERSION }}'